# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yunfei/myworld/network_ramework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yunfei/myworld/network_ramework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yunfei/myworld/network_ramework/CMakeFiles /home/yunfei/myworld/network_ramework/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yunfei/myworld/network_ramework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Master.o: src/Master.cpp.o

.PHONY : src/Master.o

# target to build an object file
src/Master.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Master.cpp.o
.PHONY : src/Master.cpp.o

src/Master.i: src/Master.cpp.i

.PHONY : src/Master.i

# target to preprocess a source file
src/Master.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Master.cpp.i
.PHONY : src/Master.cpp.i

src/Master.s: src/Master.cpp.s

.PHONY : src/Master.s

# target to generate assembly for a file
src/Master.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Master.cpp.s
.PHONY : src/Master.cpp.s

src/opCodes.o: src/opCodes.cpp.o

.PHONY : src/opCodes.o

# target to build an object file
src/opCodes.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/opCodes.cpp.o
.PHONY : src/opCodes.cpp.o

src/opCodes.i: src/opCodes.cpp.i

.PHONY : src/opCodes.i

# target to preprocess a source file
src/opCodes.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/opCodes.cpp.i
.PHONY : src/opCodes.cpp.i

src/opCodes.s: src/opCodes.cpp.s

.PHONY : src/opCodes.s

# target to generate assembly for a file
src/opCodes.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/opCodes.cpp.s
.PHONY : src/opCodes.cpp.s

src/share/PosixDaemon.o: src/share/PosixDaemon.cpp.o

.PHONY : src/share/PosixDaemon.o

# target to build an object file
src/share/PosixDaemon.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/PosixDaemon.cpp.o
.PHONY : src/share/PosixDaemon.cpp.o

src/share/PosixDaemon.i: src/share/PosixDaemon.cpp.i

.PHONY : src/share/PosixDaemon.i

# target to preprocess a source file
src/share/PosixDaemon.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/PosixDaemon.cpp.i
.PHONY : src/share/PosixDaemon.cpp.i

src/share/PosixDaemon.s: src/share/PosixDaemon.cpp.s

.PHONY : src/share/PosixDaemon.s

# target to generate assembly for a file
src/share/PosixDaemon.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/PosixDaemon.cpp.s
.PHONY : src/share/PosixDaemon.cpp.s

src/share/StackTrace.o: src/share/StackTrace.cpp.o

.PHONY : src/share/StackTrace.o

# target to build an object file
src/share/StackTrace.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/StackTrace.cpp.o
.PHONY : src/share/StackTrace.cpp.o

src/share/StackTrace.i: src/share/StackTrace.cpp.i

.PHONY : src/share/StackTrace.i

# target to preprocess a source file
src/share/StackTrace.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/StackTrace.cpp.i
.PHONY : src/share/StackTrace.cpp.i

src/share/StackTrace.s: src/share/StackTrace.cpp.s

.PHONY : src/share/StackTrace.s

# target to generate assembly for a file
src/share/StackTrace.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/StackTrace.cpp.s
.PHONY : src/share/StackTrace.cpp.s

src/share/buffer.o: src/share/buffer.cpp.o

.PHONY : src/share/buffer.o

# target to build an object file
src/share/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/buffer.cpp.o
.PHONY : src/share/buffer.cpp.o

src/share/buffer.i: src/share/buffer.cpp.i

.PHONY : src/share/buffer.i

# target to preprocess a source file
src/share/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/buffer.cpp.i
.PHONY : src/share/buffer.cpp.i

src/share/buffer.s: src/share/buffer.cpp.s

.PHONY : src/share/buffer.s

# target to generate assembly for a file
src/share/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/buffer.cpp.s
.PHONY : src/share/buffer.cpp.s

src/share/byteBuffer.o: src/share/byteBuffer.cpp.o

.PHONY : src/share/byteBuffer.o

# target to build an object file
src/share/byteBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/byteBuffer.cpp.o
.PHONY : src/share/byteBuffer.cpp.o

src/share/byteBuffer.i: src/share/byteBuffer.cpp.i

.PHONY : src/share/byteBuffer.i

# target to preprocess a source file
src/share/byteBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/byteBuffer.cpp.i
.PHONY : src/share/byteBuffer.cpp.i

src/share/byteBuffer.s: src/share/byteBuffer.cpp.s

.PHONY : src/share/byteBuffer.s

# target to generate assembly for a file
src/share/byteBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/byteBuffer.cpp.s
.PHONY : src/share/byteBuffer.cpp.s

src/share/config.o: src/share/config.cpp.o

.PHONY : src/share/config.o

# target to build an object file
src/share/config.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/config.cpp.o
.PHONY : src/share/config.cpp.o

src/share/config.i: src/share/config.cpp.i

.PHONY : src/share/config.i

# target to preprocess a source file
src/share/config.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/config.cpp.i
.PHONY : src/share/config.cpp.i

src/share/config.s: src/share/config.cpp.s

.PHONY : src/share/config.s

# target to generate assembly for a file
src/share/config.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/share/config.cpp.s
.PHONY : src/share/config.cpp.s

src/worldPacket.o: src/worldPacket.cpp.o

.PHONY : src/worldPacket.o

# target to build an object file
src/worldPacket.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/worldPacket.cpp.o
.PHONY : src/worldPacket.cpp.o

src/worldPacket.i: src/worldPacket.cpp.i

.PHONY : src/worldPacket.i

# target to preprocess a source file
src/worldPacket.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/worldPacket.cpp.i
.PHONY : src/worldPacket.cpp.i

src/worldPacket.s: src/worldPacket.cpp.s

.PHONY : src/worldPacket.s

# target to generate assembly for a file
src/worldPacket.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/worldPacket.cpp.s
.PHONY : src/worldPacket.cpp.s

src/worldSocket.o: src/worldSocket.cpp.o

.PHONY : src/worldSocket.o

# target to build an object file
src/worldSocket.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/worldSocket.cpp.o
.PHONY : src/worldSocket.cpp.o

src/worldSocket.i: src/worldSocket.cpp.i

.PHONY : src/worldSocket.i

# target to preprocess a source file
src/worldSocket.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/worldSocket.cpp.i
.PHONY : src/worldSocket.cpp.i

src/worldSocket.s: src/worldSocket.cpp.s

.PHONY : src/worldSocket.s

# target to generate assembly for a file
src/worldSocket.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/worldSocket.cpp.s
.PHONY : src/worldSocket.cpp.s

src/worldSocketMgr.o: src/worldSocketMgr.cpp.o

.PHONY : src/worldSocketMgr.o

# target to build an object file
src/worldSocketMgr.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/worldSocketMgr.cpp.o
.PHONY : src/worldSocketMgr.cpp.o

src/worldSocketMgr.i: src/worldSocketMgr.cpp.i

.PHONY : src/worldSocketMgr.i

# target to preprocess a source file
src/worldSocketMgr.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/worldSocketMgr.cpp.i
.PHONY : src/worldSocketMgr.cpp.i

src/worldSocketMgr.s: src/worldSocketMgr.cpp.s

.PHONY : src/worldSocketMgr.s

# target to generate assembly for a file
src/worldSocketMgr.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/worldSocketMgr.cpp.s
.PHONY : src/worldSocketMgr.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Master.o"
	@echo "... src/Master.i"
	@echo "... src/Master.s"
	@echo "... src/opCodes.o"
	@echo "... src/opCodes.i"
	@echo "... src/opCodes.s"
	@echo "... src/share/PosixDaemon.o"
	@echo "... src/share/PosixDaemon.i"
	@echo "... src/share/PosixDaemon.s"
	@echo "... src/share/StackTrace.o"
	@echo "... src/share/StackTrace.i"
	@echo "... src/share/StackTrace.s"
	@echo "... src/share/buffer.o"
	@echo "... src/share/buffer.i"
	@echo "... src/share/buffer.s"
	@echo "... src/share/byteBuffer.o"
	@echo "... src/share/byteBuffer.i"
	@echo "... src/share/byteBuffer.s"
	@echo "... src/share/config.o"
	@echo "... src/share/config.i"
	@echo "... src/share/config.s"
	@echo "... src/worldPacket.o"
	@echo "... src/worldPacket.i"
	@echo "... src/worldPacket.s"
	@echo "... src/worldSocket.o"
	@echo "... src/worldSocket.i"
	@echo "... src/worldSocket.s"
	@echo "... src/worldSocketMgr.o"
	@echo "... src/worldSocketMgr.i"
	@echo "... src/worldSocketMgr.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

