#!/bin/bash

cd boost_1_60_0/

./bootstrap.sh --prefix=/home/yunfei/myworld/network_ramework/dep/boost

./bjam install

cd -

cd glog-0.3.3/

./configure --prefix=/home/yunfei/myworld/network_ramework/dep/glog

make;make install

cd -
